##############################################################################
##
##  Please add report definition in a new line to make it easier
##  for script based sanity checks
##
##################################################

reports=dell.idrac.powersupply

report.dell.idrac.powersupply.name=Power Supply Statistics
report.dell.idrac.powersupply.columns=InputVoltage
report.dell.idrac.powersupply.type=nodeSnmp
report.dell.idrac.powersupply.command=--title="Power Supply Statistics" \
 DEF:context={rrd1}:InputVoltage:AVERAGE \
 DEF:minContext={rrd1}:InputVoltage:MIN \
 DEF:maxContext={rrd1}:InputVoltage:MAX \
 CDEF:floatc=context,1,/ \
 CDEF:minFloatc=minContext,1,/ \
 CDEF:maxFloatc=maxContext,1,/ \
 LINE2:floatc#0000ff:"Input Voltage" \
 GPRINT:floatc:AVERAGE:"Avg \\: %10.2lf %s" \
 GPRINT:floatc:MIN:"Min \\: %10.2lf %s" \
 GPRINT:floatc:MAX:"Max \\: %10.2lf %s\\n"

